export const PhoneSlides = [
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
      "Drag & Drop Product Listing",
      " Get advance admin dashboard",
      " Get Enquiry on WhatsApp/Email",
      " 3 months SMM Promotion",
      " Call to action",
      " Business Logo Design",
      " Get Full dynamic application",
      " Branding with Optimized SEO",
      " Get 1 year maintainance",
    ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
      "Drag & Drop Product Listing",
      " Get advance admin dashboard",
      " Get Enquiry on WhatsApp/Email",
      " 3 months SMM Promotion",
      " Call to action",
      " Business Logo Design",
      " Get Full dynamic application",
      " Branding with Optimized SEO",
      " Get 1 year maintainance",
    ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
];

export const DesktopSlides = [
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up /n and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up /n and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
  {
    heading: "Premium Plan",
    paragraph: "Get your business up and running",
    charge: "3999/m",
    features: [
        "Drag & Drop Product Listing",
        " Get advance admin dashboard",
        " Get Enquiry on WhatsApp/Email",
        " 3 months SMM Promotion",
        " Call to action",
        " Business Logo Design",
        " Get Full dynamic application",
        " Branding with Optimized SEO",
        " Get 1 year maintainance",
      ],
  },
];
